version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Thunderbird.Api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Thunderbird.GameRules"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/Thunderbird.Api.Tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/Thunderbird.Api"
    schedule:
      interval: "weekly"
